"use client";

import React, { useState, useEffect } from "react";
import { motion } from "motion/react";
import {
  Bot,
  User,
  Calendar,
  MapPin,
  Clock,
  ChevronRight,
  MessageSquare,
  Filter,
} from "lucide-react";

interface AiLead {
  id: string;
  destination: string;
  travelerName: string;
  travelerEmail: string;
  travelerPhone: string;
  numberOfDays: number;
  notes: string;
  stage: string;
  createdAt: string;
  source: string;
  activity?: Array<{
    description: string;
    createdAt: string;
  }>;
}

export default function AiLeadsPage() {
  const [leads, setLeads] = useState<AiLead[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedLead, setSelectedLead] = useState<AiLead | null>(null);
  const [filterStage, setFilterStage] = useState<string>("all");

  useEffect(() => {
    fetchLeads();
  }, []);

  const fetchLeads = async () => {
    try {
      const res = await fetch("/api/leads");
      if (res.ok) {
        const data = await res.json();
        const aiLeads = data.filter(
          (lead: AiLead) =>
            lead.source === "AI_PLANNER" ||
            lead.notes?.includes("AI Planner") ||
            lead.notes?.includes("AI Concierge")
        );
        setLeads(aiLeads);
      }
    } catch (err) {
      console.error("Failed to fetch leads:", err);
    } finally {
      setLoading(false);
    }
  };

  const filteredLeads =
    filterStage === "all"
      ? leads
      : leads.filter((l) => l.stage === filterStage);

  const getStageColor = (stage: string) => {
    const colors: Record<string, string> = {
      NEW: "bg-blue-100 text-blue-700",
      QUALIFIED: "bg-green-100 text-green-700",
      CONTACTED: "bg-yellow-100 text-yellow-700",
      MEETING: "bg-purple-100 text-purple-700",
      QUOTED: "bg-orange-100 text-orange-700",
      NEGOTIATION: "bg-red-100 text-red-700",
      WON: "bg-green-500 text-white",
    };
    return colors[stage] || "bg-slate-100 text-slate-700";
  };

  const parseItineraryFromNotes = (notes: string) => {
    const itineraryMatch = notes?.match(/Itinerary:\n([\s\S]*?)(?=\n\n|$)/);
    if (itineraryMatch) {
      return itineraryMatch[1].trim();
    }
    return null;
  };

  const parseConversationFromNotes = (notes: string) => {
    const convMatch = notes?.match(/Conversation:\n([\s\S]*?)$/);
    if (convMatch) {
      return convMatch[1].trim();
    }
    return null;
  };

  if (loading) {
    return (
      <div className="p-6">
        <div className="animate-pulse space-y-4">
          <div className="h-8 bg-slate-200 rounded w-1/3" />
          <div className="h-4 bg-slate-200 rounded w-1/2" />
          <div className="space-y-3 mt-6">
            {[1, 2, 3].map((i) => (
              <div key={i} className="h-24 bg-slate-100 rounded-xl" />
            ))}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="p-6">
      <div className="mb-6">
        <h1 className="text-2xl font-serif font-bold text-slate-900 flex items-center gap-2">
          <Bot className="w-6 h-6 text-orange-500" />
          AI Planner Leads
        </h1>
        <p className="text-slate-500 text-sm mt-1">
          Leads generated by the AI Holiday Planner
        </p>
      </div>

      <div className="flex items-center gap-4 mb-6">
        <div className="flex items-center gap-2">
          <Filter className="w-4 h-4 text-slate-400" />
          <select
            value={filterStage}
            onChange={(e) => setFilterStage(e.target.value)}
            className="px-3 py-1.5 bg-white border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-orange-500 outline-none"
          >
            <option value="all">All Stages</option>
            <option value="NEW">New</option>
            <option value="QUALIFIED">Qualified</option>
            <option value="CONTACTED">Contacted</option>
            <option value="MEETING">Meeting</option>
            <option value="QUOTED">Quoted</option>
            <option value="WON">Won</option>
          </select>
        </div>
        <span className="text-sm text-slate-500">
          {filteredLeads.length} lead{filteredLeads.length !== 1 ? "s" : ""}
        </span>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1 space-y-3 max-h-[calc(100vh-200px)] overflow-y-auto">
          {filteredLeads.length === 0 ? (
            <div className="text-center py-12 text-slate-400">
              <Bot className="w-12 h-12 mx-auto mb-3 text-slate-300" />
              <p>No AI planner leads yet</p>
            </div>
          ) : (
            filteredLeads.map((lead) => (
              <motion.button
                key={lead.id}
                type="button"
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => setSelectedLead(lead)}
                className={`w-full p-4 bg-white border rounded-xl text-left transition-all cursor-pointer ${
                  selectedLead?.id === lead.id
                    ? "border-orange-500 shadow-md"
                    : "border-slate-100 hover:border-slate-200"
                }`}
              >
                <div className="flex items-start justify-between">
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <MapPin className="w-4 h-4 text-orange-500" />
                      <span className="font-semibold text-slate-900">
                        {lead.destination}
                      </span>
                    </div>
                    <p className="text-sm text-slate-500">{lead.travelerName}</p>
                  </div>
                  <span
                    className={`text-[10px] font-bold px-2 py-1 rounded-full ${getStageColor(
                      lead.stage
                    )}`}
                  >
                    {lead.stage}
                  </span>
                </div>
                <div className="flex items-center gap-3 mt-2 text-xs text-slate-400">
                  <span className="flex items-center gap-1">
                    <Calendar className="w-3 h-3" />
                    {lead.numberOfDays} days
                  </span>
                  <span className="flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    {new Date(lead.createdAt).toLocaleDateString()}
                  </span>
                </div>
              </motion.button>
            ))
          )}
        </div>

        <div className="lg:col-span-2">
          {selectedLead ? (
            <div className="bg-white border border-slate-100 rounded-xl p-6">
              <div className="flex items-center justify-between mb-6">
                <div>
                  <h2 className="text-xl font-serif font-bold text-slate-900">
                    {selectedLead.destination}
                  </h2>
                  <p className="text-slate-500">
                    {selectedLead.travelerName} • {selectedLead.travelerEmail}
                  </p>
                </div>
                <span
                  className={`text-xs font-bold px-3 py-1 rounded-full ${getStageColor(
                    selectedLead.stage
                  )}`}
                >
                  {selectedLead.stage}
                </span>
              </div>

              <div className="grid grid-cols-2 gap-4 mb-6">
                <div className="p-3 bg-slate-50 rounded-xl">
                  <p className="text-xs text-slate-500 mb-1">Duration</p>
                  <p className="font-semibold text-slate-900">
                    {selectedLead.numberOfDays} days
                  </p>
                </div>
                <div className="p-3 bg-slate-50 rounded-xl">
                  <p className="text-xs text-slate-500 mb-1">Phone</p>
                  <p className="font-semibold text-slate-900">
                    {selectedLead.travelerPhone || "Not provided"}
                  </p>
                </div>
              </div>

              {selectedLead.notes && (
                <>
                  {parseItineraryFromNotes(selectedLead.notes) && (
                    <div className="mb-6">
                      <h3 className="text-sm font-bold text-slate-700 mb-2 flex items-center gap-2">
                        <MapPin className="w-4 h-4 text-orange-500" />
                        Generated Itinerary
                      </h3>
                      <div className="p-4 bg-orange-50 rounded-xl text-sm text-slate-700 whitespace-pre-line">
                        {parseItineraryFromNotes(selectedLead.notes)}
                      </div>
                    </div>
                  )}

                  {parseConversationFromNotes(selectedLead.notes) && (
                    <div>
                      <h3 className="text-sm font-bold text-slate-700 mb-2 flex items-center gap-2">
                        <MessageSquare className="w-4 h-4 text-orange-500" />
                        Conversation History
                      </h3>
                      <div className="p-4 bg-slate-50 rounded-xl text-sm text-slate-600 max-h-64 overflow-y-auto whitespace-pre-line">
                        {parseConversationFromNotes(selectedLead.notes)}
                      </div>
                    </div>
                  )}
                </>
              )}
            </div>
          ) : (
            <div className="bg-white border border-slate-100 rounded-xl p-12 text-center">
              <Bot className="w-16 h-16 mx-auto mb-4 text-slate-300" />
              <h3 className="text-lg font-semibold text-slate-700 mb-2">
                Select a Lead
              </h3>
              <p className="text-slate-500 text-sm">
                Click on a lead from the list to view full details
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
